-- Private database schema for Personal & Family Command Center
-- Run this in the Supabase SQL editor AFTER creating the project.
-- Authentication is handled by Supabase Auth; passwords are never stored in this app.

create table if not exists public.user_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  currency text not null default 'EGP',
  monthly_income numeric not null default 0,
  core_wealth numeric not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.monthly_budget (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  month date not null,
  category text not null,
  amount numeric not null default 0,
  priority text not null default 'variable',
  notes text,
  created_at timestamptz not null default now(),
  unique(user_id, month, category)
);

create table if not exists public.investment_positions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  asset text not null,
  quantity numeric not null default 0,
  unit text,
  cost_basis numeric not null default 0,
  market_value numeric,
  notes text,
  updated_at timestamptz not null default now()
);

create table if not exists public.goals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  target_amount numeric,
  saved_amount numeric not null default 0,
  priority text not null default 'medium',
  status text not null default 'active',
  notes text
);

alter table public.user_settings enable row level security;
alter table public.monthly_budget enable row level security;
alter table public.investment_positions enable row level security;
alter table public.goals enable row level security;

create policy "own settings" on public.user_settings for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own budget" on public.monthly_budget for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own investments" on public.investment_positions for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own goals" on public.goals for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
