-- V2 extension for the Personal & Family Command Center
-- Run AFTER supabase-schema.sql in Supabase SQL Editor.

alter table public.user_settings add column if not exists monthly_investment_target numeric not null default 0;
alter table public.user_settings add column if not exists emergency_buffer_target numeric not null default 0;
alter table public.user_settings add column if not exists personal_note text;

create table if not exists public.mobility_plans (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  option_name text not null,
  fuel_type text not null default 'petrol',
  target_price numeric not null default 0,
  saved_amount numeric not null default 0,
  monthly_contribution numeric not null default 0,
  estimated_monthly_running_cost numeric not null default 0,
  status text not null default 'considering',
  notes text,
  updated_at timestamptz not null default now()
);

create table if not exists public.career_tasks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  track text not null default 'Cloud',
  status text not null default 'planned',
  target_date date,
  notes text,
  updated_at timestamptz not null default now()
);

alter table public.mobility_plans enable row level security;
alter table public.career_tasks enable row level security;

drop policy if exists "own mobility" on public.mobility_plans;
create policy "own mobility" on public.mobility_plans for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "own career" on public.career_tasks;
create policy "own career" on public.career_tasks for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
